# Generated by Django 5.0.6 on 2024-06-13 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rack_no', models.IntegerField()),
                ('depth', models.IntegerField(db_index=True)),
                ('pallet_positions', models.IntegerField(db_index=True)),
                ('filled_pallet_poitions', models.IntegerField(blank=True, db_index=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('address', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='RackLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_id', models.CharField(max_length=32, unique=True)),
                ('coordinates', models.JSONField(blank=True, null=True)),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twdt.rack')),
            ],
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet_id', models.CharField(max_length=64, unique=True)),
                ('owner', models.CharField(db_index=True, max_length=256)),
                ('product_code', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField()),
                ('quantity_on_hand', models.IntegerField()),
                ('age', models.IntegerField()),
                ('balance_shelve_life_to_expire', models.IntegerField()),
                ('product_group', models.CharField(db_index=True, max_length=64)),
                ('rack_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twdt.racklocation')),
            ],
        ),
        migrations.AddField(
            model_name='rack',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twdt.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='racklocation',
            constraint=models.UniqueConstraint(fields=('rack', 'location_id'), name='rack_location__unique'),
        ),
        migrations.AddConstraint(
            model_name='pallet',
            constraint=models.UniqueConstraint(fields=('rack_location', 'pallet_id'), name='pallet__unique'),
        ),
        migrations.AddConstraint(
            model_name='rack',
            constraint=models.UniqueConstraint(fields=('warehouse', 'rack_no'), name='rack__unique'),
        ),
    ]
