# Generated by Django 5.0.6 on 2024-06-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twdt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rack',
            old_name='filled_pallet_poitions',
            new_name='filled_pallet_positions',
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='remarks',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
