# Generated by Django 5.0.6 on 2024-06-14 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twdt', '0002_rename_filled_pallet_poitions_rack_filled_pallet_positions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.date(2024, 6, 14)),
            preserve_default=False,
        ),
    ]
