# Generated by Django 5.0.6 on 2024-06-15 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twdt', '0003_pallet_expiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=64, unique=True)),
                ('expiry', models.DateTimeField()),
                ('remarks', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
