# Generated by Django 5.0.6 on 2024-06-17 01:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twdt', '0006_apikey_ip_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PalletHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(db_index=True, max_length=256)),
                ('product_code', models.CharField(db_index=True, max_length=64)),
                ('description', models.TextField()),
                ('expiry_date', models.DateTimeField()),
                ('quantity_on_hand', models.IntegerField()),
                ('age', models.IntegerField()),
                ('balance_shelve_life_to_expire', models.IntegerField()),
                ('product_group', models.CharField(db_index=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pallet_id', models.CharField(db_index=True, max_length=64)),
                ('rack_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='twdt.racklocation')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
