# Generated by Django 5.0.6 on 2024-06-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twdt', '0007_pallet_created_pallethistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pallethistory',
            options={'verbose_name_plural': 'Pallet history'},
        ),
    ]
