# Generated by Django 5.0.6 on 2024-06-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twdt', '0009_device_devicelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='devicelocation',
            name='created',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='pallethistory',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
