# Generated by Django 5.0.6 on 2024-06-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_check', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='urlgroup',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
