# Generated by Django 5.0.6 on 2024-06-25 09:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_check', '0002_notificationgroup_urlgroup_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationgroup',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationgroup',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
