# Generated by Django 5.0.6 on 2024-06-25 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_check', '0003_notificationgroup_emails_notificationgroup_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationgroup',
            name='emails',
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('notification_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='url_check.notificationgroup')),
            ],
        ),
        migrations.CreateModel(
            name='UrlCheckNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('url_check', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='url_check.urlcheck')),
            ],
        ),
    ]
