# Generated by Django 5.0.6 on 2024-06-25 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_check', '0004_remove_notificationgroup_emails_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcheck',
            name='notification_group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='url_check.notificationgroup'),
            preserve_default=False,
        ),
    ]
